# Generated by Django 5.0.9 on 2024-12-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0002_alter_role_options_alter_role_name_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
