# Generated by Django 5.0.9 on 2024-12-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0003_remove_user_is_active_remove_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
