# Generated by Django 5.0.9 on 2024-12-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0005_remove_user_email_user_birth_date_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
