# Generated by Django 5.0.9 on 2024-12-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0013_zone_attraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена услуги')),
            ],
        ),
    ]
