# Generated by Django 5.0.9 on 2024-12-16 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0014_servicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('visit_date', models.DateField(verbose_name='Дата посещения')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='coral.servicetype', verbose_name='Тип услуги')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
