# Generated by Django 5.0.9 on 2024-12-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0016_paymentmethod_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewReceipts',
            fields=[
                ('receipt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('payment_method_name', models.CharField(max_length=255)),
                ('service_type_name', models.CharField(max_length=255)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket_date', models.DateTimeField()),
                ('visitor_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'view_receipts',
                'managed': False,
            },
        ),
    ]
