# Generated by Django 5.0.9 on 2024-12-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0017_viewreceipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewUsers',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_date', models.DateField()),
                ('login', models.CharField(max_length=150)),
                ('role_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'view_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-created_at'],
            },
        ),
    ]
